name: Build Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    # checkout
    - uses: actions/checkout@v3
    #setup Go
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    # get xcaddy
    - name: Get xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    # build caddy
    - name: Build Caddy
      run: xcaddy build
    # upload artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: caddy
        path: caddy