name: Build Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    # checkout
    - uses: actions/checkout@v3
    #setup Go
    - uses: actions/setup-go@v3
      with:
        go-version: ">=1.21.0"
    # get xcaddy
    - name: Get xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    # build caddy
    - name: Build Caddy
      run: xcaddy build
    # upload artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Caddy_${{ matrix.platform }}_${{ github.run_id }}_ListenCaddy
        path: caddy
    - if: matrix.platform == 'windows-latest'
      name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Caddy_${{ matrix.platform }}_${{ github.run_id }}_ListenCaddy.exe
        path: caddy.exe